# Generated by Django 4.2.20 on 2025-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('company_url', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('work_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=255, null=True)),
                ('workday', models.CharField(blank=True, max_length=255, null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('search_term', models.CharField(default='N/A', max_length=255)),
            ],
            options={
                'db_table': 'job_offers',
            },
        ),
    ]
